- hosts: all
  vars_files:
          -  "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
  tasks:
  - name: "Install Web Server Software"
    package:
            name: "{{ software_name }}"
            state: present

  - name: "Copy Web Page"
    template:
            src: "test.html.j2"
            dest: "{{ doc_root }}"

  - name: "Start Web Service"
    service:
            name: "{{ service_name }}"
            state: started



